### ISSUE TITLE
Symbols not displaying correctly in 'Reason' test for a violation

### ISSUE THREAD

**Issue by geierac** [dequelabs/axe-firefox-devtools#3]
Tag symbols display as HTML codes in 'Reason' text.
![image](https://cloud.githubusercontent.com/assets/13380739/8750115/96dcc90a-2c73-11e5-86cb-ac82384a991c.png)

**Comment by dylanb** [comment]
@geierac can you point me to the page where you reproduced this problem?

**Comment by geierac** [comment]
Go to http://caitlingeier.com/, analyze, and view the violation reason for
"Zooming and scaling must not be disabled."

On Fri, Jul 17, 2015 at 4:48 PM, Dylan Barrell <notifications@github.com>
wrote:

> @geierac <https://github.com/geierac> can you point me to the page where
> you reproduced this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dequelabs/axe-firefox-devtools/issues/3#issuecomment-122409808>
> .
>



-- 
Caitlin Geier
User Experience Designer
caitlin.geier@deque.com
