### ISSUE TITLE
Combobox

### ISSUE THREAD

**Issue by evanmoore** [dequelabs/axe-firefox-devtools#33]
The dev tool is reporting "Required ARIA child role not present: textbox" when we use a combobox. However, we are using the combobox correctly. 

I also tested the dev tools on this accessibility website and it also throws the same error.
http://oaa-accessibility.org/example/10/

Please investigate and resolve. let me know if you have any questions.

**Comment by WilcoFiers** [comment]
It seems to me there is a slight problem in the spec here. The textbox rule is required to be owned by the combobox element. However even in the example in ARIA itself showing how to do it there is no element which has the role of textbox, either explicitly or implicitly. I think the best thing to do here would be to set the textbox as an optional child. WDYT?

**Comment by dylanb** [comment]
@WilcoFiers could you raise an issue in the [ARIA spec project](https://github.com/w3c/html-aria) to have this clarified and in the interim, I agree with your solution

**Comment by marcysutton** [comment]
I'm going to close this issue since it's related to axe-firefox-devtools. See issue https://github.com/dequelabs/axe-core/issues/160.
