### ISSUE TITLE
aria-relevant valid value reported as false poitive

### ISSUE THREAD

**Issue by afercia** [dequelabs/axe-firefox-devtools#34]
Hello, quickly tested your nice tool, noticed a small thing that, as far as I can tell, is a false positive. An `aria-relevant` value of `additions text` reported as not valid values while, according to the specs is perfectly valid.
Error reported:
> Ensures all ARIA attributes have valid values 
> Summary:
> Fix any of the following:
>     Invalid ARIA attribute value: aria-relevant="additions text"

Specification:
https://www.w3.org/TR/wai-aria/states_and_properties
> The attribute is represented as a space delimited list of the following values: additions, removals, text; or a single catch-all value all.

**Comment by WilcoFiers** [comment]
You are absolutely correct. This is a bug that has been resolved in Attest (aXe's commercial big brother) and will be available in the next release of aXe as well. Please close the comment if you have no further questions.

**Comment by afercia** [comment]
Great :) Thanks very much.
