### ISSUE TITLE
Usability: 'Highlight' button should indicate when highlighting is active and allow user to turn highlighting off

### ISSUE THREAD

**Issue by geierac** [dequelabs/axe-firefox-devtools#4]
- When a description is chosen, highlighting is activated (if applicable), but the highlight button doesn't change state.
- When user clicks the highlight button, it's given a blue border to indicate that highlighting is on. The blue border disappears when you navigate away from the tab/window, but highlighting remains on.
- Clicking the highlight button when highlighting is active does nothing. Expected: highlighting should turn off.

Would recommend using a thicker blue border (2px or greater).

![Highlight button](https://cloud.githubusercontent.com/assets/13380739/8750416/31d1574a-2c75-11e5-9fe0-67fcdc337faf.png)

**Comment by WilcoFiers** [comment]
This issue is resolved in the newest release.
