### ISSUE TITLE
Color contrast issue for active issue in list of issues (left pane)

### ISSUE THREAD

**Issue by srinivasuchakravarthula** [dequelabs/axe-firefox-devtools#45]
Description: When an issue is selected to view details, background changes to blue and text remains black. This causes difficulty for users with low vision (like me) to read that issue again.

Steps to reproduce:
1. Open a web page (be sure to pick a page that ptotentially have accessibility problems)
2. Run aXe extension
3. Click on "Analyze" button
4. Select one of the issues from the list
5. Notice background of selected issue changes to Blue and text remains black.

Environment Noticed:
Browser: Firefox (latest)
OS; Windows 7
aXe version: 1.0.2

Screenshot: Attached
![axe-dev-tools-cc-srini](https://cloud.githubusercontent.com/assets/5158620/18792124/e87c2584-81d2-11e6-8cba-752f49f68bfb.png)

**Comment by dylanb** [comment]
@marcysutton looks like this may be a regression, can you look into this? fyi FireEyes II does not exhibit the same behavior

**Comment by marcysutton** [comment]
Yes definitely! I told Srinivasu to file an issue so it didn't get lost in the shuffle. Will check it out next week.
