### ISSUE TITLE
Usability: change column header 'Count' to 'Violations'

### ISSUE THREAD

**Issue by geierac** [dequelabs/axe-firefox-devtools#5]
'Count' is unclear - a count of what? As it's a count of the number of violations for a given criterion, naming the column 'Violations' would be more descriptive.

!['Count' column header](https://cloud.githubusercontent.com/assets/13380739/8750606/6f944ce4-2c76-11e5-8914-7f1b850eeb20.png)

**Comment by dylanb** [comment]
If we changed "Description" to "Violation" or "Violation Description", would that make the count clearer? Perhaps change "Count" to "Occurrences"? To me, calling the number of times the issue occurs, "Violations" does not accurately describe what it is.

**Comment by geierac** [comment]
Yes, using something clearer than 'Description' would make 'Count' clearer as well. Instead of 'Description,' perhaps use 'Description of Violation.' I like the idea of using 'Occurrences' instead of 'Count,' too.
