### ISSUE TITLE
Doesn't support multiple instances

### ISSUE THREAD

**Issue by zbthomas** [dequelabs/axe-firefox-devtools#52]
I have noticed that when I have multiple tabs or windows open and run the tool, the result that I get is carried over to all other tabs and windows that I have open. This makes it hard to compare more than one tab or window to another.

**Comment by marcysutton** [comment]
I can reproduce the issue in Firefox. In our Chrome extension, results are preserved for separate tabs. I would recommend using that version if you need multiple tab support right away: https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

**Comment by marcysutton** [comment]
This is no longer an issue in our new Web Extension.
