### ISSUE TITLE
Wrong browser?

### ISSUE THREAD

**Issue by evetsreklaw** [dequelabs/axe-firefox-devtools#54]
Latest update apparently puts the Chrome plugin into Firefox and is no longer available.
![axe](https://user-images.githubusercontent.com/1405187/32509862-a2ba3b44-c3bc-11e7-8d3e-6206c976f532.png)

**Comment by WilcoFiers** [comment]
Indeed it did. We noticed that as well. We'll be fixing that in 3.2.1.

**Comment by evetsreklaw** [comment]
Any estimated release date/time?

**Comment by marcysutton** [comment]
It's already fixed, we just have to ship it.

**Comment by evetsreklaw** [comment]
It is not available at all in the Dev Tools area (Windows 7/FF 52.4 ESR). Works fine on MacOS / FF 56.0.2

**Comment by marcysutton** [comment]
aXe requires Firefox 53 or higher.

**Comment by evetsreklaw** [comment]
It hasn't before, is that new?

**Comment by marcysutton** [comment]
It is new, yes. We were forced to move to Webextensions by Mozilla, and those require Firefox 53+

**Comment by evetsreklaw** [comment]
Thank you for the update. You can close this.
