### ISSUE TITLE
Firefox Console keyboard shortcut Conflicts

### ISSUE THREAD

**Issue by KatieK2** [dequelabs/axe-firefox-devtools#59]
When I use "Control Shift k" in Firefox, I expect to get the browser dev tools with focus on the Console tab. However, with the aXe 3.2.1 extension enabled, I instead get a red error box saying "No textarea elements on this page". I get the results that I expect when the aXe extension is disabled in Firefox.

This is on Firefox for Windows 10. The same problem does not exist in Firefox for OSX, probably because the keyboard shortcut for the dev tools Console is different. I recommend finding an alternate keyboard shortcut for Firefox in Windows.

**Comment by marcysutton** [comment]
Hi Katie, which version of Firefox? I just tested it in Nightly (59) and I don't have that problem. Ctrl + Shift + K takes me to the Devtools console with no errors.

**Comment by KatieK2** [comment]
Hi Marcy, 

This is on on Firefox Quantum v57.0.2 (64-bit) in Windows 10. I was sure that it was aXe because the problem went away when I disabled aXe (and left all other extensions enabled). I can't explain that part. But now I see that the error box has Ghost Text (another extension) labeling in the dom. Darn computers.

Sorry for the false alarm!

**Comment by marcysutton** [comment]
No problem, thanks for the contribution Katie!
