### ISSUE TITLE
Usability: heading for violation details is unclear

### ISSUE THREAD

**Issue by geierac** [dequelabs/axe-firefox-devtools#6]
Violation details are labeled simply "17 of 23" with no descriptive text. Recommendations:

1. Repeat the description of the criterion above the violation navigation so that users have a more obvious reference to what they're looking at.
2. Label the violation navigation something like "Viewing violation 17 of 23".

Violation navigation:
![violation navigation](https://cloud.githubusercontent.com/assets/13380739/8750723/27175d7a-2c77-11e5-882a-223e310dcf16.png)

**Comment by dylanb** [comment]
I would like to see some user testing with this one - given that the number of occurrences is listed in the table next to the item that was just clicked-on, I think these numbers should be quite understandable. perhaps this issue is fixable by addressing #5

**Comment by geierac** [comment]
The problem I had with this was more that the column highlighting in the violations list was insufficient. I kept forgetting which group of problems I was looking at. Regardless of how the violations list is labeled, I do think labeling this whole section more clearly would still be better for usability.
