### ISSUE TITLE
Usability: Default font size should be larger.

### ISSUE THREAD

**Issue by geierac** [dequelabs/axe-firefox-devtools#7]
The font size for all text is very small at 100% zoom. Would recommend using a font size at least as big as is used for the developer tool headers. The font size should at least 12px; ideally 16px.

Font size very small compared to headings:
![font size](https://cloud.githubusercontent.com/assets/13380739/8750876/e7c2a264-2c77-11e5-9331-2ef1e6b45909.png)

**Comment by dylanb** [comment]
I would like to recommend changing this issue to "use the Firefox themes" i.e. get the extension to leverage the theme settings of Firefox when using font colors, sizes etc. Thoughts?

**Comment by geierac** [comment]
If that means the default font size would be at least as big at that of the developer tool headers, then that would be fine. My main concern is that the default font size now would be too small for many users to read comfortably without modification (zooming, etc.).
